/*
     Company: 达梦数据库有限公司
  Department: 达梦技术公司/产品研发中心
      Author: 毕艺翔
      E-mail: byx@dameng.com
      Create: 2021/5/17 14:27
     Project: dmctl
     Package: pkg
    Describe: Todo
*/

package pkg

import "dmctl/internal/pkg/business/v1/common/typed"

//Attribute： 静态/ 静态-系统级：0 ，手动：1 ，动态-会话级：2，动态-系统级：3
var DmIni = map[string]*typed.DmIni{
	"CTL_PATH":                          {Name: "CTL_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"CTL_BAK_PATH":                      {Name: "CTL_BAK_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"CTL_BAK_NUM":                       {Name: "CTL_BAK_NUM", Attribute: 1, DefaultValue: "10", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"SYSTEM_PATH":                       {Name: "SYSTEM_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"CONFIG_PATH":                       {Name: "CONFIG_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"TEMP_PATH":                         {Name: "TEMP_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"BAK_PATH":                          {Name: "BAK_PATH", Attribute: 1, DefaultValue: "安装时指定 ", ValueType: "varchar", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"BAK_POLICY":                        {Name: "BAK_POLICY", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "控制文件相关参数（注意： 本类参数不建议用户修改）"},
	"INSTANCE_NAME":                     {Name: "INSTANCE_NAME", Attribute: 1, DefaultValue: "DMSERVER ", ValueType: "varchar", Describe: "", Group: "实例名"},
	"MAX_OS_MEMORY":                     {Name: "MAX_OS_MEMORY", Attribute: 0, DefaultValue: "100", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_POOL":                       {Name: "MEMORY_POOL", Attribute: 0, DefaultValue: "200", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_N_POOLS":                    {Name: "MEMORY_N_POOLS", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_TARGET":                     {Name: "MEMORY_TARGET", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_EXTENT_SIZE":                {Name: "MEMORY_EXTENT_SIZE", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_LEAK_CHECK":                 {Name: "MEMORY_LEAK_CHECK", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_MAGIC_CHECK":                {Name: "MEMORY_MAGIC_CHECK", Attribute: 0, DefaultValue: "2", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HUGEPAGE_THRESHOLD":                {Name: "HUGEPAGE_THRESHOLD", Attribute: 3, DefaultValue: "32", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MEMORY_BAK_POOL":                   {Name: "MEMORY_BAK_POOL", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HUGE_MEMORY_PERCENTAGE":            {Name: "HUGE_MEMORY_PERCENTAGE", Attribute: 0, DefaultValue: "50", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HUGE_BUFFER":                       {Name: "HUGE_BUFFER", Attribute: 0, DefaultValue: "80", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HUGE_BUFFER_POOLS":                 {Name: "HUGE_BUFFER_POOLS", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"BUFFER":                            {Name: "BUFFER", Attribute: 0, DefaultValue: "100", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"BUFFER_POOLS":                      {Name: "BUFFER_POOLS", Attribute: 0, DefaultValue: "19", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"FAST_POOL_PAGES":                   {Name: "FAST_POOL_PAGES", Attribute: 0, DefaultValue: "3000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"FAST_ROLL_PAGES":                   {Name: "FAST_ROLL_PAGES", Attribute: 0, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"KEEP":                              {Name: "KEEP", Attribute: 0, DefaultValue: "8", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"RECYCLE":                           {Name: "RECYCLE", Attribute: 0, DefaultValue: "64", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"RECYCLE_POOLS":                     {Name: "RECYCLE_POOLS", Attribute: 0, DefaultValue: "19", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MULTI_PAGE_GET_NUM":                {Name: "MULTI_PAGE_GET_NUM", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"PRELOAD_SCAN_NUM":                  {Name: "PRELOAD_SCAN_NUM", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"PRELOAD_EXTENT_NUM":                {Name: "PRELOAD_EXTENT_NUM", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SORT_FLAG":                         {Name: "SORT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SORT_BUF_SIZE":                     {Name: "SORT_BUF_SIZE", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SORT_BUF_GLOBAL_SIZE":              {Name: "SORT_BUF_GLOBAL_SIZE", Attribute: 3, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SORT_BLK_SIZE":                     {Name: "SORT_BLK_SIZE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HAGR_HASH_SIZE":                    {Name: "HAGR_HASH_SIZE", Attribute: 2, DefaultValue: "100000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MAL_LEAK_CHECK":                    {Name: "MAL_LEAK_CHECK", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HJ_BUF_GLOBAL_SIZE":                {Name: "HJ_BUF_GLOBAL_SIZE", Attribute: 3, DefaultValue: "500", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HJ_BUF_SIZE":                       {Name: "HJ_BUF_SIZE", Attribute: 2, DefaultValue: "50", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HJ_BLK_SIZE":                       {Name: "HJ_BLK_SIZE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HAGR_BUF_GLOBAL_SIZE":              {Name: "HAGR_BUF_GLOBAL_SIZE", Attribute: 3, DefaultValue: "500", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HAGR_BUF_SIZE":                     {Name: "HAGR_BUF_SIZE", Attribute: 2, DefaultValue: "50", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HAGR_BLK_SIZE":                     {Name: "HAGR_BLK_SIZE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MTAB_MEM_SIZE":                     {Name: "MTAB_MEM_SIZE", Attribute: 0, DefaultValue: "8", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"FTAB_MEM_SIZE":                     {Name: "FTAB_MEM_SIZE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MMT_SIZE":                          {Name: "MMT_SIZE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MMT_GLOBAL_SIZE":                   {Name: "MMT_GLOBAL_SIZE", Attribute: 3, DefaultValue: "4000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"MMT_FLAG":                          {Name: "MMT_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"DICT_BUF_SIZE":                     {Name: "DICT_BUF_SIZE", Attribute: 0, DefaultValue: "5", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HFS_CACHE_SIZE":                    {Name: "HFS_CACHE_SIZE", Attribute: 3, DefaultValue: "160", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"VM_STACK_SIZE":                     {Name: "VM_STACK_SIZE", Attribute: 0, DefaultValue: "256", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"VM_POOL_SIZE":                      {Name: "VM_POOL_SIZE", Attribute: 0, DefaultValue: "64", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"VM_POOL_TARGET":                    {Name: "VM_POOL_TARGET", Attribute: 0, DefaultValue: "32768", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SESS_POOL_SIZE":                    {Name: "SESS_POOL_SIZE", Attribute: 3, DefaultValue: "64", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SESS_POOL_TARGET":                  {Name: "SESS_POOL_TARGET", Attribute: 3, DefaultValue: "32768", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"RT_HEAP_TARGET":                    {Name: "RT_HEAP_TARGET", Attribute: 3, DefaultValue: "8192", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"VM_MEM_HEAP":                       {Name: "VM_MEM_HEAP", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"RFIL_RECV_BUF_SIZE":                {Name: "RFIL_RECV_BUF_SIZE", Attribute: 0, DefaultValue: "16", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"COLDATA_POOL_SIZE":                 {Name: "COLDATA_POOL_SIZE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"HAGR_DISTINCT_HASH_TABLE_SIZE":     {Name: "HAGR_DISTINCT_HASH_TABLE_SIZE", Attribute: 2, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"CNNTB_HASH_TABLE_SIZE":             {Name: "CNNTB_HASH_TABLE_SIZE", Attribute: 2, DefaultValue: "100", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"GLOBAL_RTREE_BUF_SIZE":             {Name: "GLOBAL_RTREE_BUF_SIZE", Attribute: 2, DefaultValue: "100", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SINGLE_RTREE_BUF_SIZE":             {Name: "SINGLE_RTREE_BUF_SIZE", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"SORT_OPT_SIZE":                     {Name: "SORT_OPT_SIZE", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"TSORT_OPT":                         {Name: "TSORT_OPT", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "内存相关参数"},
	"WORKER_THREADS":                    {Name: "WORKER_THREADS", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"TASK_THREADS":                      {Name: "TASK_THREADS", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"FAST_RW_LOCK":                      {Name: "FAST_RW_LOCK", Attribute: 1, DefaultValue: "1", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"SPIN_TIME":                         {Name: "SPIN_TIME", Attribute: 0, DefaultValue: "4000", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"WORK_THRD_STACK_SIZE":              {Name: "WORK_THRD_STACK_SIZE", Attribute: 0, DefaultValue: "8192", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"WORK_THRD_RESERVE_SIZE":            {Name: "WORK_THRD_RESERVE_SIZE", Attribute: 0, DefaultValue: "100", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"WORKER_CPU_PERCENT":                {Name: "WORKER_CPU_PERCENT", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"NESTED_C_STYLE_COMMENT":            {Name: "NESTED_C_STYLE_COMMENT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "线程相关参数"},
	"USE_PLN_POOL":                      {Name: "USE_PLN_POOL", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DYN_SQL_CAN_CACHE":                 {Name: "DYN_SQL_CAN_CACHE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RS_CAN_CACHE":                      {Name: "RS_CAN_CACHE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RS_CACHE_TABLES":                   {Name: "RS_CACHE_TABLES", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "查询相关参数"},
	"RS_CACHE_MIN_TIME":                 {Name: "RS_CACHE_MIN_TIME", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RS_BDTA_FLAG":                      {Name: "RS_BDTA_FLAG", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RS_BDTA_BUF_SIZE":                  {Name: "RS_BDTA_BUF_SIZE", Attribute: 0, DefaultValue: "32", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RESULT_SET_LIMIT":                  {Name: "RESULT_SET_LIMIT", Attribute: 2, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"RESULT_SET_FOR_QUERY":              {Name: "RESULT_SET_FOR_QUERY", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"SESSION_RESULT_SET_LIMIT":          {Name: "SESSION_RESULT_SET_LIMIT", Attribute: 3, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"BUILD_FORWARD_RS":                  {Name: "BUILD_FORWARD_RS", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MAX_OPT_N_TABLES":                  {Name: "MAX_OPT_N_TABLES", Attribute: 2, DefaultValue: "6", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MAX_N_GRP_PUSH_DOWN":               {Name: "MAX_N_GRP_PUSH_DOWN", Attribute: 2, DefaultValue: "5", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CNNTB_MAX_LEVEL":                   {Name: "CNNTB_MAX_LEVEL", Attribute: 2, DefaultValue: "20000", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CTE_MAXRECURSION":                  {Name: "CTE_MAXRECURSION", Attribute: 2, DefaultValue: "100", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CTE_OPT_FLAG":                      {Name: "CTE_OPT_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"BATCH_PARAM_OPT":                   {Name: "BATCH_PARAM_OPT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CLT_CONST_TO_PARAM":                {Name: "CLT_CONST_TO_PARAM", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"LIKE_OPT_FLAG":                     {Name: "LIKE_OPT_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"FILTER_PUSH_DOWN":                  {Name: "FILTER_PUSH_DOWN", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_MCLCT":                         {Name: "USE_MCLCT", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MPP_OP_JUMP":                       {Name: "MPP_OP_JUMP", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"PHF_NTTS_OPT":                      {Name: "PHF_NTTS_OPT", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MPP_MOTION_SYNC":                   {Name: "MPP_MOTION_SYNC", Attribute: 2, DefaultValue: "200", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_FTTS":                          {Name: "USE_FTTS", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"UPD_DEL_OPT":                       {Name: "UPD_DEL_OPT", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_DIST_IN_SUBQUERY_OPT":       {Name: "ENABLE_DIST_IN_SUBQUERY_OPT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MAX_OPT_N_OR_BEXPS":                {Name: "MAX_OPT_N_OR_BEXPS", Attribute: 2, DefaultValue: "7", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_HAGR_FLAG":                     {Name: "USE_HAGR_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DTABLE_PULLUP_FLAG":                {Name: "DTABLE_PULLUP_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"VIEW_PULLUP_FLAG":                  {Name: "VIEW_PULLUP_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"VIEW_PULLUP_MAX_TAB":               {Name: "VIEW_PULLUP_MAX_TAB", Attribute: 2, DefaultValue: "7", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"STR_NULL_OPS_COMPATIBLE":           {Name: "STR_NULL_OPS_COMPATIBLE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"GROUP_OPT_FLAG":                    {Name: "GROUP_OPT_FLAG", Attribute: 2, DefaultValue: "4", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"FROM_OPT_FLAG":                     {Name: "FROM_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HAGR_PARALLEL_OPT_FLAG":            {Name: "HAGR_PARALLEL_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HAGR_DISTINCT_OPT_FLAG":            {Name: "HAGR_DISTINCT_OPT_FLAG", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"REFED_EXISTS_OPT_FLAG":             {Name: "REFED_EXISTS_OPT_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"REFED_OPS_SUBQUERY_OPT_FLAG":       {Name: "REFED_OPS_SUBQUERY_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MAX_PHC_BE_NUM":                    {Name: "MAX_PHC_BE_NUM", Attribute: 2, DefaultValue: "512", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"PARTIAL_JOIN_EVALUATION_FLAG":      {Name: "PARTIAL_JOIN_EVALUATION_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_FK_REMOVE_TABLES_FLAG":         {Name: "USE_FK_REMOVE_TABLES_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_FJ_REMOVE_TABLE_FLAG":          {Name: "USE_FJ_REMOVE_TABLE_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"SLCT_ERR_PROCESS_FLAG":             {Name: "SLCT_ERR_PROCESS_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MPP_HASH_LR_RATE":                  {Name: "MPP_HASH_LR_RATE", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"LPQ_HASH_LR_RATE":                  {Name: "LPQ_HASH_LR_RATE", Attribute: 2, DefaultValue: "30", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_HTAB":                          {Name: "USE_HTAB", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"SEL_ITEM_HTAB_FLAG":                {Name: "SEL_ITEM_HTAB_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OR_CVT_HTAB_FLAG":                  {Name: "OR_CVT_HTAB_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CASE_WHEN_CVT_IFUN":                {Name: "CASE_WHEN_CVT_IFUN", Attribute: 2, DefaultValue: "9", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OR_NBEXP_CVT_CASE_WHEN_FLAG":       {Name: "OR_NBEXP_CVT_CASE_WHEN_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"NONCONST_OR_CVT_IN_LST_FLAG":       {Name: "NONCONST_OR_CVT_IN_LST_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OUTER_CVT_INNER_PULL_UP_COND_FLAG": {Name: "OUTER_CVT_INNER_PULL_UP_COND_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPT_OR_FOR_HUGE_TABLE_FLAG":        {Name: "OPT_OR_FOR_HUGE_TABLE_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ORDER_BY_NULLS_FLAG":               {Name: "ORDER_BY_NULLS_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"SUBQ_CVT_SPL_FLAG":                 {Name: "SUBQ_CVT_SPL_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_RQ_TO_SPL":                  {Name: "ENABLE_RQ_TO_SPL", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MULTI_IN_CVT_EXISTS":               {Name: "MULTI_IN_CVT_EXISTS", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"PRJT_REPLACE_NPAR":                 {Name: "PRJT_REPLACE_NPAR", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_RQ_TO_INV":                  {Name: "ENABLE_RQ_TO_INV", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"SUBQ_EXP_CVT_FLAG":                 {Name: "SUBQ_EXP_CVT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_REFER_TAB_ONLY":                {Name: "USE_REFER_TAB_ONLY", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"REFED_SUBQ_CROSS_FLAG":             {Name: "REFED_SUBQ_CROSS_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"IN_LIST_AS_JOIN_KEY":               {Name: "IN_LIST_AS_JOIN_KEY", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OUTER_JOIN_INDEX_OPT_FLAG":         {Name: "OUTER_JOIN_INDEX_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OUTER_JOIN_FLATING_FLAG":           {Name: "OUTER_JOIN_FLATING_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"TOP_ORDER_OPT_FLAG":                {Name: "TOP_ORDER_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"TOP_DIS_HASH_FLAG":                 {Name: "TOP_DIS_HASH_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_RQ_TO_NONREF_SPL":           {Name: "ENABLE_RQ_TO_NONREF_SPL", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPTIMIZER_MODE":                    {Name: "OPTIMIZER_MODE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"NEW_MOTION":                        {Name: "NEW_MOTION", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"LDIS_NEW_FOLD_FUN":                 {Name: "LDIS_NEW_FOLD_FUN", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DYNAMIC_CALC_NODES":                {Name: "DYNAMIC_CALC_NODES", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPTIMIZER_MAX_PERM":                {Name: "OPTIMIZER_MAX_PERM", Attribute: 2, DefaultValue: "7200", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_INDEX_FILTER":               {Name: "ENABLE_INDEX_FILTER", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPTIMIZER_DYNAMIC_SAMPLING":        {Name: "OPTIMIZER_DYNAMIC_SAMPLING", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"AUTO_STAT_OBJ":                     {Name: "AUTO_STAT_OBJ", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"NONREFED_SUBQUERY_AS_CONST":        {Name: "NONREFED_SUBQUERY_AS_CONST", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HASH_CMP_OPT_FLAG":                 {Name: "HASH_CMP_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OUTER_OPT_NLO_FLAG":                {Name: "OUTER_OPT_NLO_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DISTINCT_USE_INDEX_SKIP":           {Name: "DISTINCT_USE_INDEX_SKIP", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"USE_INDEX_SKIP_SCAN":               {Name: "USE_INDEX_SKIP_SCAN", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"INDEX_SKIP_SCAN_RATE":              {Name: "INDEX_SKIP_SCAN_RATE", Attribute: 2, DefaultValue: "0.0025", ValueType: "double", Describe: "", Group: "查询相关参数"},
	"SPEED_SEMI_JOIN_PLAN":              {Name: "SPEED_SEMI_JOIN_PLAN", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"COMPLEX_VIEW_MERGING":              {Name: "COMPLEX_VIEW_MERGING", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OP_SUBQ_CVT_IN_FLAG":               {Name: "OP_SUBQ_CVT_IN_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HLSM_FLAG":                         {Name: "HLSM_FLAG", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DEL_HP_OPT_FLAG":                   {Name: "DEL_HP_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPTIMIZER_OR_NBEXP":                {Name: "OPTIMIZER_OR_NBEXP", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CNNTB_OPT_FLAG":                    {Name: "CNNTB_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ADAPTIVE_NPLN_FLAG":                {Name: "ADAPTIVE_NPLN_FLAG", Attribute: 2, DefaultValue: "3", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MULTI_UPD_OPT_FLAG":                {Name: "MULTI_UPD_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"MULTI_UPD_MAX_COL_NUM":             {Name: "MULTI_UPD_MAX_COL_NUM", Attribute: 2, DefaultValue: "128", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENHANCE_BIND_PEEKING":              {Name: "ENHANCE_BIND_PEEKING", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"NBEXP_OPT_FLAG":                    {Name: "NBEXP_OPT_FLAG", Attribute: 2, DefaultValue: "3", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HAGR_HASH_ALGORITHM_FLAG":          {Name: "HAGR_HASH_ALGORITHM_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"DIST_HASH_ALGORITHM_FLAG":          {Name: "DIST_HASH_ALGORITHM_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"UNPIVOT_ORDER_FLAG":                {Name: "UNPIVOT_ORDER_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"VIEW_FILTER_MERGING":               {Name: "VIEW_FILTER_MERGING", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"OPT_MEM_CHECK":                     {Name: "OPT_MEM_CHECK", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_JOIN_FACTORIZATION":         {Name: "ENABLE_JOIN_FACTORIZATION", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ERROR_COMPATIBLE_FLAG":             {Name: "ERROR_COMPATIBLE_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_PARTITION_WISE_OPT":         {Name: "ENABLE_PARTITION_WISE_OPT", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"EXPLAIN_SHOW_FACTOR":               {Name: "EXPLAIN_SHOW_FACTOR", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"HASH_PLL_OPT_FLAG":                 {Name: "HASH_PLL_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"PLACE_GROUP_BY_FLAG":               {Name: "PLACE_GROUP_BY_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_NEST_LOOP_JOIN_CACHE":       {Name: "ENABLE_NEST_LOOP_JOIN_CACHE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_DBLINK_TO_INV":              {Name: "ENABLE_DBLINK_TO_INV", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_BLOB_CMP_FLAG":              {Name: "ENABLE_BLOB_CMP_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_CREATE_BM_INDEX_FLAG":       {Name: "ENABLE_CREATE_BM_INDEX_FLAG", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CVIEW_STAR_WITH_PREFIX":            {Name: "CVIEW_STAR_WITH_PREFIX", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_ADJUST_NLI_COST":            {Name: "ENABLE_ADJUST_NLI_COST", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"ENABLE_SEQ_REUSE":                  {Name: "ENABLE_SEQ_REUSE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "查询相关参数"},
	"CKPT_RLOG_SIZE":                    {Name: "CKPT_RLOG_SIZE", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"CKPT_DIRTY_PAGES":                  {Name: "CKPT_DIRTY_PAGES", Attribute: 3, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"CKPT_INTERVAL":                     {Name: "CKPT_INTERVAL", Attribute: 3, DefaultValue: "300", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"CKPT_FLUSH_RATE":                   {Name: "CKPT_FLUSH_RATE", Attribute: 3, DefaultValue: "5", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"CKPT_FLUSH_PAGES":                  {Name: "CKPT_FLUSH_PAGES", Attribute: 3, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"CKPT_WAIT_PAGES":                   {Name: "CKPT_WAIT_PAGES", Attribute: 3, DefaultValue: "128", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"FORCE_FLUSH_PAGES":                 {Name: "FORCE_FLUSH_PAGES", Attribute: 3, DefaultValue: "8", ValueType: "int", Describe: "", Group: "检查点相关参数"},
	"DIRECT_IO":                         {Name: "DIRECT_IO", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "IO 相关参数"},
	"IO_THR_GROUPS":                     {Name: "IO_THR_GROUPS", Attribute: 0, DefaultValue: "2", ValueType: "int", Describe: "", Group: "IO 相关参数"},
	"HIO_THR_GROUPS":                    {Name: "HIO_THR_GROUPS", Attribute: 0, DefaultValue: "2", ValueType: "int", Describe: "", Group: "IO 相关参数"},
	"FAST_EXTEND_WITH_DS":               {Name: "FAST_EXTEND_WITH_DS", Attribute: 3, DefaultValue: "LINUX/AIX/BSD 缺省为 1， 其他缺省 0 ", ValueType: "int", Describe: "", Group: "IO 相关参数"},
	"FIL_CHECK_INTERVAL":                {Name: "FIL_CHECK_INTERVAL", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "IO 相关参数"},
	"MAX_SESSIONS":                      {Name: "MAX_SESSIONS", Attribute: 0, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_CONCURRENT_TRX":                {Name: "MAX_CONCURRENT_TRX", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"CONCURRENT_TRX_MODE":               {Name: "CONCURRENT_TRX_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"CONCURRENT_DELAY":                  {Name: "CONCURRENT_DELAY", Attribute: 3, DefaultValue: "16", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TRX_VIEW_SIZE":                     {Name: "TRX_VIEW_SIZE", Attribute: 0, DefaultValue: "512", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TRX_VIEW_MODE":                     {Name: "TRX_VIEW_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TRX_CMTARR_SIZE":                   {Name: "TRX_CMTARR_SIZE", Attribute: 0, DefaultValue: "10", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_SESSION_STATEMENT":             {Name: "MAX_SESSION_STATEMENT", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_SESSION_MEMORY":                {Name: "MAX_SESSION_MEMORY", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_CONCURRENT_OLAP_QUERY":         {Name: "MAX_CONCURRENT_OLAP_QUERY", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BIG_TABLE_THRESHHOLD":              {Name: "BIG_TABLE_THRESHHOLD", Attribute: 2, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_EP_SITES":                      {Name: "MAX_EP_SITES", Attribute: 1, DefaultValue: "64", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PORT_NUM":                          {Name: "PORT_NUM", Attribute: 0, DefaultValue: "5236", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"LISTEN_IP":                         {Name: "LISTEN_IP", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "数据库相关参数"},
	"FAST_LOGIN":                        {Name: "FAST_LOGIN", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"DDL_AUTO_COMMIT":                   {Name: "DDL_AUTO_COMMIT", Attribute: 1, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"COMPRESS_MODE":                     {Name: "COMPRESS_MODE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PK_WITH_CLUSTER":                   {Name: "PK_WITH_CLUSTER", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"EXPR_N_LEVEL":                      {Name: "EXPR_N_LEVEL", Attribute: 2, DefaultValue: "200", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"N_PARSE_LEVEL":                     {Name: "N_PARSE_LEVEL", Attribute: 2, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_SQL_LEVEL":                     {Name: "MAX_SQL_LEVEL", Attribute: 3, DefaultValue: "500", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BDTA_SIZE":                         {Name: "BDTA_SIZE", Attribute: 0, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"OLAP_FLAG":                         {Name: "OLAP_FLAG", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"JOIN_HASH_SIZE":                    {Name: "JOIN_HASH_SIZE", Attribute: 2, DefaultValue: "500000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HFILES_OPENED":                     {Name: "HFILES_OPENED", Attribute: 0, DefaultValue: "256", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"FAST_COMMIT":                       {Name: "FAST_COMMIT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ISO_IGNORE":                        {Name: "ISO_IGNORE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TEMP_SIZE":                         {Name: "TEMP_SIZE", Attribute: 0, DefaultValue: "10", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TEMP_SPACE_LIMIT":                  {Name: "TEMP_SPACE_LIMIT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"FILE_TRACE":                        {Name: "FILE_TRACE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"COMM_TRACE":                        {Name: "COMM_TRACE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ERROR_TRACE":                       {Name: "ERROR_TRACE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"CACHE_POOL_SIZE":                   {Name: "CACHE_POOL_SIZE", Attribute: 0, DefaultValue: "20", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PLN_DICT_HASH_THRESHOLD":           {Name: "PLN_DICT_HASH_THRESHOLD", Attribute: 0, DefaultValue: "20", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"STAT_COLLECT_SIZE":                 {Name: "STAT_COLLECT_SIZE", Attribute: 2, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"STAT_ALL":                          {Name: "STAT_ALL", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TABLE_STAT_FLAG":                   {Name: "TABLE_STAT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PHC_MODE_ENFORCE":                  {Name: "PHC_MODE_ENFORCE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_HASH_JOIN":                  {Name: "ENABLE_HASH_JOIN", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_INDEX_JOIN":                 {Name: "ENABLE_INDEX_JOIN", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_MERGE_JOIN":                 {Name: "ENABLE_MERGE_JOIN", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MPP_INDEX_JOIN_OPT_FLAG":           {Name: "MPP_INDEX_JOIN_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MPP_NLI_OPT_FLAG":                  {Name: "MPP_NLI_OPT_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MAX_PARALLEL_DEGREE":               {Name: "MAX_PARALLEL_DEGREE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PARALLEL_POLICY":                   {Name: "PARALLEL_POLICY", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PARALLEL_THRD_NUM":                 {Name: "PARALLEL_THRD_NUM", Attribute: 0, DefaultValue: "10", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PARALLEL_MODE_COMMON_DEGREE":       {Name: "PARALLEL_MODE_COMMON_DEGREE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PUSH_SUBQ":                         {Name: "PUSH_SUBQ", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"OPTIMIZER_AGGR_GROUPBY_ELIM":       {Name: "OPTIMIZER_AGGR_GROUPBY_ELIM", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"UPD_TAB_INFO":                      {Name: "UPD_TAB_INFO", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_IN_VALUE_LIST_OPT":          {Name: "ENABLE_IN_VALUE_LIST_OPT", Attribute: 2, DefaultValue: "6", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENHANCED_BEXP_TRANS_GEN":           {Name: "ENHANCED_BEXP_TRANS_GEN", Attribute: 2, DefaultValue: "3", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_DIST_VIEW_UPDATE":           {Name: "ENABLE_DIST_VIEW_UPDATE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"STAR_TRANSFORMATION_ENABLED":       {Name: "STAR_TRANSFORMATION_ENABLED", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"MONITOR_INDEX_FLAG":                {Name: "MONITOR_INDEX_FLAG", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"RAISE_CASE_NOT_FOUND":              {Name: "RAISE_CASE_NOT_FOUND", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"FIRST_ROWS":                        {Name: "FIRST_ROWS", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"LIST_TABLE":                        {Name: "LIST_TABLE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_SPACELIMIT_CHECK":           {Name: "ENABLE_SPACELIMIT_CHECK", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BUILD_VERTICAL_PK_BTREE":           {Name: "BUILD_VERTICAL_PK_BTREE", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BDTA_PACKAGE_COMPRESS":             {Name: "BDTA_PACKAGE_COMPRESS", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HFINS_PARALLEL_FLAG":               {Name: "HFINS_PARALLEL_FLAG", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HFINS_MAX_THRD_NUM":                {Name: "HFINS_MAX_THRD_NUM", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"LINK_CONN_KEEP_TIME":               {Name: "LINK_CONN_KEEP_TIME", Attribute: 0, DefaultValue: "15", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"DETERMIN_CACHE_SIZE":               {Name: "DETERMIN_CACHE_SIZE", Attribute: 2, DefaultValue: "5", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"NTYPE_MAX_OBJ_NUM":                 {Name: "NTYPE_MAX_OBJ_NUM", Attribute: 3, DefaultValue: "1000000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"CTAB_SEL_WITH_CONS":                {Name: "CTAB_SEL_WITH_CONS", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_BUF_SIZE":                     {Name: "HLDR_BUF_SIZE", Attribute: 3, DefaultValue: "8", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_BUF_TOTAL_SIZE":               {Name: "HLDR_BUF_TOTAL_SIZE", Attribute: 3, DefaultValue: "4294967294", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_REPAIR_FLAG":                  {Name: "HLDR_REPAIR_FLAG", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_FORCE_COLUMN_STORAGE":         {Name: "HLDR_FORCE_COLUMN_STORAGE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_FORCE_COLUMN_STORAGE_PERCENT": {Name: "HLDR_FORCE_COLUMN_STORAGE_PERCENT", Attribute: 3, DefaultValue: "80", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_HOLD_RATE":                    {Name: "HLDR_HOLD_RATE", Attribute: 3, DefaultValue: "1.5", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HLDR_MAX_RATE":                     {Name: "HLDR_MAX_RATE", Attribute: 3, DefaultValue: "2", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HUGE_ACID":                         {Name: "HUGE_ACID", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HUGE_STAT_MODE":                    {Name: "HUGE_STAT_MODE", Attribute: 2, DefaultValue: "2", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HFS_CHECK_SUM":                     {Name: "HFS_CHECK_SUM", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HBUF_DATA_MODE":                    {Name: "HBUF_DATA_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"DBLINK_OPT_FLAG":                   {Name: "DBLINK_OPT_FLAG", Attribute: 2, DefaultValue: "509", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"FILL_COL_DESC_FLAG":                {Name: "FILL_COL_DESC_FLAG", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BTR_SPLIT_MODE":                    {Name: "BTR_SPLIT_MODE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BLOB_OUTROW_REC_STOR":              {Name: "BLOB_OUTROW_REC_STOR", Attribute: 3, DefaultValue: "5", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TS_RESERVED_EXTENTS":               {Name: "TS_RESERVED_EXTENTS", Attribute: 0, DefaultValue: "64", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TS_SAFE_FREE_EXTENTS":              {Name: "TS_SAFE_FREE_EXTENTS", Attribute: 0, DefaultValue: "512", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TS_MAX_ID":                         {Name: "TS_MAX_ID", Attribute: 0, DefaultValue: "8192", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TS_FIL_MAX_ID":                     {Name: "TS_FIL_MAX_ID", Attribute: 0, DefaultValue: "255", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"DECIMAL_FIX_STORAGE":               {Name: "DECIMAL_FIX_STORAGE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"SQL_SAFE_UPDATE_ROWS":              {Name: "SQL_SAFE_UPDATE_ROWS", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ENABLE_HUGE_SECIND":                {Name: "ENABLE_HUGE_SECIND", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"LOB_MAX_INROW_LEN":                 {Name: "LOB_MAX_INROW_LEN", Attribute: 3, DefaultValue: "900", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"RS_PRE_FETCH":                      {Name: "RS_PRE_FETCH", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TIMER_TRIG_CHECK_INTERVAL":         {Name: "TIMER_TRIG_CHECK_INTERVAL", Attribute: 3, DefaultValue: "60", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"INNER_INDEX_DDL_SHOW":              {Name: "INNER_INDEX_DDL_SHOW", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"HP_STAT_SAMPLE_COUNT":              {Name: "HP_STAT_SAMPLE_COUNT", Attribute: 3, DefaultValue: "50", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"PWR_FLUSH_PAGES":                   {Name: "PWR_FLUSH_PAGES", Attribute: 3, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"REDO_UNTIL_LSN":                    {Name: "REDO_UNTIL_LSN", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "数据库相关参数"},
	"IGNORE_FILE_SYS_CHECK":             {Name: "IGNORE_FILE_SYS_CHECK", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"FILE_SCAN_PERCENT":                 {Name: "FILE_SCAN_PERCENT", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"STARTUP_CHECKPOINT":                {Name: "STARTUP_CHECKPOINT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"CHECK_SVR_VERSION":                 {Name: "CHECK_SVR_VERSION", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"ID_RECYCLE_FLAG":                   {Name: "ID_RECYCLE_FLAG", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"BAK_USE_AP":                        {Name: "BAK_USE_AP", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"TRXID_UNCOVERED":                   {Name: "TRXID_UNCOVERED", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"GEN_SQL_MEM_RECLAIM":               {Name: "GEN_SQL_MEM_RECLAIM", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据库相关参数"},
	"LOAD_TABLE":                        {Name: "LOAD_TABLE", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "预先装载表相关参数"},
	"LOAD_HTABLE":                       {Name: "LOAD_HTABLE", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "预先装载表相关参数"},
	"CLT_CACHE_TABLES":                  {Name: "CLT_CACHE_TABLES", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "客户端缓存"},
	"RLOG_BUF_SIZE":                     {Name: "RLOG_BUF_SIZE", Attribute: 0, DefaultValue: "512", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_POOL_SIZE":                    {Name: "RLOG_POOL_SIZE", Attribute: 0, DefaultValue: "256", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_PARALLEL_ENABLE":              {Name: "RLOG_PARALLEL_ENABLE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_IGNORE_TABLE_SET":             {Name: "RLOG_IGNORE_TABLE_SET", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_APPEND_LOGIC":                 {Name: "RLOG_APPEND_LOGIC", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_APPEND_SYSTAB_LOGIC":          {Name: "RLOG_APPEND_SYSTAB_LOGIC", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_CHECK_SPACE":                  {Name: "RLOG_CHECK_SPACE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_SAFE_SPACE":                   {Name: "RLOG_SAFE_SPACE", Attribute: 0, DefaultValue: "128", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_RESERVE_THRESHOLD":            {Name: "RLOG_RESERVE_THRESHOLD", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_RESERVE_SIZE":                 {Name: "RLOG_RESERVE_SIZE", Attribute: 3, DefaultValue: "4096", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_SEND_APPLY_MON":               {Name: "RLOG_SEND_APPLY_MON", Attribute: 0, DefaultValue: "64", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_COMPRESS_LEVEL":               {Name: "RLOG_COMPRESS_LEVEL", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_ENC_CMPR_THREAD":              {Name: "RLOG_ENC_CMPR_THREAD", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"RLOG_PKG_SEND_ECPR_ONLY":           {Name: "RLOG_PKG_SEND_ECPR_ONLY", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"DFS_RLOG_SEND_POLICY":              {Name: "DFS_RLOG_SEND_POLICY", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDO_PWR_OPT":                      {Name: "REDO_PWR_OPT", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDO_IGNORE_DB_VERSION":            {Name: "REDO_IGNORE_DB_VERSION", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"ELOG_REPORT_LINK_SQL":              {Name: "ELOG_REPORT_LINK_SQL", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDO_BUF_SIZE":                     {Name: "REDO_BUF_SIZE", Attribute: 0, DefaultValue: "64", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_BUF_SIZE":                    {Name: "REDOS_BUF_SIZE", Attribute: 0, DefaultValue: "1024", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_BUF_NUM":                     {Name: "REDOS_BUF_NUM", Attribute: 0, DefaultValue: "4096", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_MAX_DELAY":                   {Name: "REDOS_MAX_DELAY", Attribute: 0, DefaultValue: "1800", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_PRE_LOAD":                    {Name: "REDOS_PRE_LOAD", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_PARALLEL_NUM":                {Name: "REDOS_PARALLEL_NUM", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"REDOS_ENABLE_SELECT":               {Name: "REDOS_ENABLE_SELECT", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "REDO 日志相关参数"},
	"ISOLATION_LEVEL":                   {Name: "ISOLATION_LEVEL", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"DDL_WAIT_TIME":                     {Name: "DDL_WAIT_TIME", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"BLDR_WAIT_TIME":                    {Name: "BLDR_WAIT_TIME", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"MPP_WAIT_TIME":                     {Name: "MPP_WAIT_TIME", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"FAST_RELEASE_SLOCK":                {Name: "FAST_RELEASE_SLOCK", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"SESS_CHECK_INTERVAL":               {Name: "SESS_CHECK_INTERVAL", Attribute: 2, DefaultValue: "3", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"LOCK_TID_MODE":                     {Name: "LOCK_TID_MODE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"LOCK_TID_UPGRADE":                  {Name: "LOCK_TID_UPGRADE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"NOWAIT_WHEN_UNIQUE_CONFLICT":       {Name: "NOWAIT_WHEN_UNIQUE_CONFLICT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"UNDO_EXTENT_NUM":                   {Name: "UNDO_EXTENT_NUM", Attribute: 0, DefaultValue: "4", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"MAX_DE_TIMEOUT":                    {Name: "MAX_DE_TIMEOUT", Attribute: 2, DefaultValue: "10", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"TRX_RLOG_WAIT_MODE":                {Name: "TRX_RLOG_WAIT_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"TRANSACTIONS":                      {Name: "TRANSACTIONS", Attribute: 0, DefaultValue: "75", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"MVCC_RETRY_TIMES":                  {Name: "MVCC_RETRY_TIMES", Attribute: 0, DefaultValue: "5", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"MVCC_PAGE_OPT":                     {Name: "MVCC_PAGE_OPT", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"ENABLE_FLASHBACK":                  {Name: "ENABLE_FLASHBACK", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"UNDO_RETENTION":                    {Name: "UNDO_RETENTION", Attribute: 3, DefaultValue: "90", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"PARALLEL_PURGE_FLAG":               {Name: "PARALLEL_PURGE_FLAG", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"PURGE_WAIT_TIME":                   {Name: "PURGE_WAIT_TIME", Attribute: 3, DefaultValue: "500", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"PSEG_RECV":                         {Name: "PSEG_RECV", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"ENABLE_IGNORE_PURGE_REC":           {Name: "ENABLE_IGNORE_PURGE_REC", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"ROLL_ON_ERR":                       {Name: "ROLL_ON_ERR", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"XA_TRX_IDLE_TIME":                  {Name: "XA_TRX_IDLE_TIME", Attribute: 3, DefaultValue: "60", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"ENABLE_TMP_TAB_ROLLBACK":           {Name: "ENABLE_TMP_TAB_ROLLBACK", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"LOCK_DICT_OPT":                     {Name: "LOCK_DICT_OPT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"TRX_DICT_LOCK_NUM":                 {Name: "TRX_DICT_LOCK_NUM", Attribute: 3, DefaultValue: "64", ValueType: "int", Describe: "", Group: "事务相关参数"},
	"ENABLE_ENCRYPT":                    {Name: "ENABLE_ENCRYPT", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"MIN_SSL_VERSION":                   {Name: "MIN_SSL_VERSION", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"CLIENT_UKEY":                       {Name: "CLIENT_UKEY", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"ENABLE_UDP":                        {Name: "ENABLE_UDP", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"UDP_MAX_IDLE":                      {Name: "UDP_MAX_IDLE", Attribute: 0, DefaultValue: "15", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"UDP_BTU_COUNT":                     {Name: "UDP_BTU_COUNT", Attribute: 0, DefaultValue: "8", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"AUDIT_FILE_FULL_MODE":              {Name: "AUDIT_FILE_FULL_MODE", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"AUDIT_MAX_FILE_SIZE":               {Name: "AUDIT_MAX_FILE_SIZE", Attribute: 3, DefaultValue: "100", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"AUDIT_IP_STYLE":                    {Name: "AUDIT_IP_STYLE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"MSG_COMPRESS_TYPE":                 {Name: "MSG_COMPRESS_TYPE", Attribute: 0, DefaultValue: "2", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"LDAP_HOST":                         {Name: "LDAP_HOST", Attribute: 1, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "安全相关参数"},
	"COMM_ENCRYPT_NAME":                 {Name: "COMM_ENCRYPT_NAME", Attribute: 0, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "安全相关参数"},
	"COMM_VALIDATE":                     {Name: "COMM_VALIDATE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"MESSAGE_CHECK":                     {Name: "MESSAGE_CHECK", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"EXTERNAL_JFUN_PORT":                {Name: "EXTERNAL_JFUN_PORT", Attribute: 3, DefaultValue: "6363", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"EXTERNAL_AP_PORT":                  {Name: "EXTERNAL_AP_PORT", Attribute: 3, DefaultValue: "4236", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"ENABLE_PL_SYNONYM":                 {Name: "ENABLE_PL_SYNONYM", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"FORCE_CERTIFICATE_ENCRYPTION":      {Name: "FORCE_CERTIFICATE_ENCRYPTION", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"REGEXP_MATCH_PATTERN":              {Name: "REGEXP_MATCH_PATTERN", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "安全相关参数"},
	"UNIX_SOCKET_PATHNAME":              {Name: "UNIX_SOCKET_PATHNAME", Attribute: 0, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "安全相关参数"},
	"BACKSLASH_ESCAPE":                  {Name: "BACKSLASH_ESCAPE", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"STR_LIKE_IGNORE_MATCH_END_SPACE":   {Name: "STR_LIKE_IGNORE_MATCH_END_SPACE", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"CLOB_LIKE_MAX_LEN":                 {Name: "CLOB_LIKE_MAX_LEN", Attribute: 0, DefaultValue: "10240", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"EXCLUDE_DB_NAME":                   {Name: "EXCLUDE_DB_NAME", Attribute: 0, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"MS_PARSE_PERMIT":                   {Name: "MS_PARSE_PERMIT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"COMPATIBLE_MODE":                   {Name: "COMPATIBLE_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"JSON_MODE":                         {Name: "JSON_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"DATETIME_FMT_MODE":                 {Name: "DATETIME_FMT_MODE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"DOUBLE_MODE":                       {Name: "DOUBLE_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"CASE_COMPATIBLE_MODE":              {Name: "CASE_COMPATIBLE_MODE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"XA_COMPATIBLE_MODE":                {Name: "XA_COMPATIBLE_MODE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"EXCLUDE_RESERVED_WORDS":            {Name: "EXCLUDE_RESERVED_WORDS", Attribute: 0, DefaultValue: "空串 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"COUNT_64BIT":                       {Name: "COUNT_64BIT", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"CALC_AS_DECIMAL":                   {Name: "CALC_AS_DECIMAL", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"CMP_AS_DECIMAL":                    {Name: "CMP_AS_DECIMAL", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"CAST_int_MODE":                     {Name: "CAST_int_MODE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"PL_SQLCODE_COMPATIBLE":             {Name: "PL_SQLCODE_COMPATIBLE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"LEGACY_SEQUENCE":                   {Name: "LEGACY_SEQUENCE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"DM6_TODATE_FMT":                    {Name: "DM6_TODATE_FMT", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"MILLISECOND_FMT":                   {Name: "MILLISECOND_FMT", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"NLS_DATE_FORMAT":                   {Name: "NLS_DATE_FORMAT", Attribute: 0, DefaultValue: "无 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"NLS_TIME_FORMAT":                   {Name: "NLS_TIME_FORMAT", Attribute: 0, DefaultValue: "无 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"NLS_TIMESTAMP_FORMAT":              {Name: "NLS_TIMESTAMP_FORMAT", Attribute: 0, DefaultValue: "无 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"NLS_TIME_TZ_FORMAT":                {Name: "NLS_TIME_TZ_FORMAT", Attribute: 0, DefaultValue: "无 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"NLS_TIMESTAMP_TZ_FORMAT":           {Name: "NLS_TIMESTAMP_TZ_FORMAT", Attribute: 0, DefaultValue: "无 ", ValueType: "varchar", Describe: "", Group: "兼容性相关参数"},
	"PK_MAP_TO_DIS":                     {Name: "PK_MAP_TO_DIS", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"DROP_CASCADE_VIEW":                 {Name: "DROP_CASCADE_VIEW", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"PROXY_PROTOCOL_MODE":               {Name: "PROXY_PROTOCOL_MODE", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"SPACE_COMPARE_MODE":                {Name: "SPACE_COMPARE_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "兼容性相关参数"},
	"SVR_LOG":                           {Name: "SVR_LOG", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "用户请求跟踪相关参数"},
	"SVR_LOG_NAME":                      {Name: "SVR_LOG_NAME", Attribute: 3, DefaultValue: "SLOG_ALL", ValueType: "varchar", Describe: "", Group: "用户请求跟踪相关参数"},
	"GDB_THREAD_INFO":                   {Name: "GDB_THREAD_INFO", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "系统跟踪相关参数"},
	"TRACE_PATH":                        {Name: "TRACE_PATH", Attribute: 1, DefaultValue: "SYSTEM_PATH", ValueType: "varchar", Describe: "", Group: "系统跟踪相关参数"},
	"SVR_OUTPUT":                        {Name: "SVR_OUTPUT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "系统跟踪相关参数"},
	"SVR_ELOG_FREQ":                     {Name: "SVR_ELOG_FREQ", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "系统跟踪相关参数"},
	"ENABLE_OSLOG":                      {Name: "ENABLE_OSLOG", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "系统跟踪相关参数"},
	"ENABLE_MONITOR":                    {Name: "ENABLE_MONITOR", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"MONITOR_TIME":                      {Name: "MONITOR_TIME", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"MONITOR_SYNC_EVENT":                {Name: "MONITOR_SYNC_EVENT", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"MONITOR_SQL_EXEC":                  {Name: "MONITOR_SQL_EXEC", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"ENABLE_FREQROOTS":                  {Name: "ENABLE_FREQROOTS", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"MAX_FREQ_ROOTS":                    {Name: "MAX_FREQ_ROOTS", Attribute: 0, DefaultValue: "200000", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"MIN_FREQ_CNT":                      {Name: "MIN_FREQ_CNT", Attribute: 0, DefaultValue: "100000", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"LARGE_MEM_THRESHOLD":               {Name: "LARGE_MEM_THRESHOLD", Attribute: 3, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"ENABLE_MONITOR_DMSQL":              {Name: "ENABLE_MONITOR_DMSQL", Attribute: 2, DefaultValue: "1", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"ENABLE_TIMER_TRIG_LOG":             {Name: "ENABLE_TIMER_TRIG_LOG", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"IO_TIMEOUT":                        {Name: "IO_TIMEOUT", Attribute: 3, DefaultValue: "300", ValueType: "int", Describe: "", Group: "MONITOR 监控相关参数"},
	"DW_ERROR_TIME":                     {Name: "DW_ERROR_TIME", Attribute: 3, DefaultValue: "60", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"DW_PORT":                           {Name: "DW_PORT", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"ALTER_MODE_STATUS":                 {Name: "ALTER_MODE_STATUS", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"ENABLE_OFFLINE_TS":                 {Name: "ENABLE_OFFLINE_TS", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"SESS_FREE_IN_SUSPEND":              {Name: "SESS_FREE_IN_SUSPEND", Attribute: 3, DefaultValue: "60", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"SUSPEND_WORKER_TIMEOUT":            {Name: "SUSPEND_WORKER_TIMEOUT", Attribute: 3, DefaultValue: "600", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"SUSPENDING_FORBIDDEN":              {Name: "SUSPENDING_FORBIDDEN", Attribute: 1, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"DW_CONSISTENCY_CHECK":              {Name: "DW_CONSISTENCY_CHECK", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "数据守护相关参数"},
	"CTI_HASH_SIZE":                     {Name: "CTI_HASH_SIZE", Attribute: 2, DefaultValue: "100000", ValueType: "int", Describe: "", Group: "全文索引相关参数"},
	"CTI_HASH_BUF_SIZE":                 {Name: "CTI_HASH_BUF_SIZE", Attribute: 2, DefaultValue: "50", ValueType: "int", Describe: "", Group: "全文索引相关参数"},
	"USE_FORALL_ATTR":                   {Name: "USE_FORALL_ATTR", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "全文索引相关参数"},
	"ALTER_TABLE_OPT":                   {Name: "ALTER_TABLE_OPT", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "全文索引相关参数"},
	"MAL_INI":                           {Name: "MAL_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"ARCH_INI":                          {Name: "ARCH_INI", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"REP_INI":                           {Name: "REP_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"LLOG_INI":                          {Name: "LLOG_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"TIMER_INI":                         {Name: "TIMER_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"MPP_INI":                           {Name: "MPP_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "配置文件相关参数"},
	"IDLE_MEM_THRESHOLD":                {Name: "IDLE_MEM_THRESHOLD", Attribute: 3, DefaultValue: "50", ValueType: "int", Describe: "", Group: "其他"},
	"IDLE_DISK_THRESHOLD":               {Name: "IDLE_DISK_THRESHOLD", Attribute: 3, DefaultValue: "1000", ValueType: "int", Describe: "", Group: "其他"},
	"IDLE_SESS_THRESHOLD":               {Name: "IDLE_SESS_THRESHOLD", Attribute: 3, DefaultValue: "5", ValueType: "int", Describe: "", Group: "其他"},
	"ENABLE_PRISVC":                     {Name: "ENABLE_PRISVC", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "其他"},
	"ENABLE_INJECT_HINT":                {Name: "ENABLE_INJECT_HINT", Attribute: 2, DefaultValue: "0", ValueType: "int", Describe: "", Group: "其他"},
	"FETCH_PACKAGE_SIZE":                {Name: "FETCH_PACKAGE_SIZE", Attribute: 3, DefaultValue: "512", ValueType: "int", Describe: "", Group: "其他"},
	"DSC_N_CTLS":                        {Name: "DSC_N_CTLS", Attribute: 0, DefaultValue: "10000", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_N_POOLS":                       {Name: "DSC_N_POOLS", Attribute: 0, DefaultValue: "2", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_TRX_CMT_LSN_SYNC":              {Name: "DSC_TRX_CMT_LSN_SYNC", Attribute: 3, DefaultValue: "3", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_GBS_REVOKE_OPT":                {Name: "DSC_GBS_REVOKE_OPT", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_ENABLE_MONITOR":                {Name: "DSC_ENABLE_MONITOR", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_TRX_VIEW_SYNC":                 {Name: "DSC_TRX_VIEW_SYNC", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_REMOTE_READ_MODE":              {Name: "DSC_REMOTE_READ_MODE", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_FILE_INIT_ASYNC":               {Name: "DSC_FILE_INIT_ASYNC", Attribute: 1, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_TRX_CMT_OPT":                   {Name: "DSC_TRX_CMT_OPT", Attribute: 1, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DSC_RESERVE_PERCENT":               {Name: "DSC_RESERVE_PERCENT", Attribute: 3, DefaultValue: "0.08", ValueType: "double", Describe: "", Group: "DSC 相关参数"},
	"HA_INST_CHECK_IP":                  {Name: "HA_INST_CHECK_IP", Attribute: 1, DefaultValue: "需要在 HA 场景下指定 ", ValueType: "varchar", Describe: "", Group: "DSC 相关参数"},
	"HA_INST_CHECK_PORT":                {Name: "HA_INST_CHECK_PORT", Attribute: 1, DefaultValue: "65534", ValueType: "int", Describe: "", Group: "DSC 相关参数"},
	"DFS_BUF_FLUSH_OPT":                 {Name: "DFS_BUF_FLUSH_OPT", Attribute: 0, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DMTDD 相关参数"},
	"DFS_PAGE_FLUSH_VALIDATE":           {Name: "DFS_PAGE_FLUSH_VALIDATE", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "DMTDD 相关参数"},
	"DFS_PATH":                          {Name: "DFS_PATH", Attribute: 1, DefaultValue: "始化数据库服务器 DS 时指定", ValueType: "varchar", Describe: "", Group: "DMTDD 相关参数"},
	"DFS_INI":                           {Name: "DFS_INI", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "DMTDD 相关参数"},
	"PWD_POLICY":                        {Name: "PWD_POLICY", Attribute: 3, DefaultValue: "2", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"PWD_MIN_LEN":                       {Name: "PWD_MIN_LEN", Attribute: 3, DefaultValue: "9", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_OBJ_REUSE":                  {Name: "ENABLE_OBJ_REUSE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_REMOTE_OSAUTH":              {Name: "ENABLE_REMOTE_OSAUTH", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_LOCAL_OSAUTH":               {Name: "ENABLE_LOCAL_OSAUTH", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_STRICT_CHECK":               {Name: "ENABLE_STRICT_CHECK", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"MAC_LABEL_OPTION":                  {Name: "MAC_LABEL_OPTION", Attribute: 3, DefaultValue: "1", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_EXTERNAL_CALL":              {Name: "ENABLE_EXTERNAL_CALL", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"ENABLE_DDL_ANY_PRIV":               {Name: "ENABLE_DDL_ANY_PRIV", Attribute: 3, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
	"SEC_PRIV_MODE":                     {Name: "SEC_PRIV_MODE", Attribute: 0, DefaultValue: "0", ValueType: "int", Describe: "", Group: "特殊参数，不在dm.ini文件中，但是可以使用系统调用修改"},
}
